### ISSUE TITLE
Option to omit function/method parameters when type is set to `nil`

### ISSUE THREAD

**Issue by QueenOfSquiggles** [Tired-Fox/mlua-extras#8]
Hello! This crate looks quite lovely and I'm working on exploring it more and more. To my understanding, there is not a way to expose a function/method without parameters (besides `this` for the method). I did make a fork and I'm slowly teasing out the codebase to see if I can either find out the recommended solution, or if I can make a PR with this change. 

I figured opening an issue is the best way I can express what I am trying to do and maybe get some amount of guidance if I'm missing something. 

My initial attempts are to simply omit the parameter when the definition file gets generated, but I'm struggling to catch the parameters with my `if v.ty == Type::nil()`.

Anyway, thanks a ton for your work! I intend to explore more and hopefully submit a PR if I can figure out any improvements that I would want for my own projects. Feel free to take your time, I understand especially today is an odd day for many to be on here and working on code.

**Comment by QueenOfSquiggles** [comment]
Update on this, I was erroneously adding this check to the "function" definition generation rather than the "method" definition generation. Simply `v.ty == Type::nil()` returns true as expected. Though it probably isn't the best approach since a `nil` default value is likely a valid approach for an API in Lua. I'm still digging further into how functions are registered and looking for where I can make changes to support zero-parameter methods and functions

**Comment by QueenOfSquiggles** [comment]
I made a PR (#9 ) which has an example script how to do exactly what I was trying to do. I feel a bit dumb since the exact same pattern is used in Bevy and I've done coding in Bevy for a while now

**Comment by Tired-Fox** [comment]
@QueenOfSquiggles I appreciate you reaching out and doing the research!

I wrote the typing portion of the crate as a layer on top of `mlua` that collects the type information while keeping at least the same API. While it wasn't explicit in this crate, `mlua` has a zero argument function/method written using empty `()`. Since this crate just collects the type information, the goal is to interpret it how `mlua` would, as "nothing".

I will merge your PR as the example is useful.

If you have more ideas, issues, quality of life changes, etc... feel free to reach out.
